package com.art.hellospringboot.hello;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;

import com.art.hellospringboot.hello.config.CodeCampConﬁg;
import com.art.hellospringboot.hello.modelled.BankAccountRepository;

@SpringBootApplication
@EnableConfigurationProperties(CodeCampConﬁg.class) 
public class HelloApplication {
	@Autowired private CodeCampConﬁg conﬁg; 
	//private static final String  = null;
	@Autowired // This means to get the bean called userRepository              
	// Which is auto-generated by Spring, we will use it to handle the data  
	private BankAccountRepository bankRepository;           
	
	public static void main(String[] args) { 
	SpringApplication.run(HelloApplication.class, args); }   
	
	@Bean
	public CommandLineRunner commandLineRunner(ApplicationContext ctx){ 
	return args -> {// System.out.println("Test Test");
	//BankAccount account = new BankAccount("Oak", "Test", new BigDecimal(10000), 0); 
	//bankRepository.save(account); 
	};
	}

	@Bean
	public CommandLineRunner commandLineRunner2(ApplicationContext ctx){
		return args -> { 
			System.out.println("Test Configuration");
			CodeCampConﬁg config= new CodeCampConﬁg();
			System.out.println("language = "+ config.getLanguage());
			System.out.println("student = "+ config.getStudent());
		};
	}
}
